apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: jeysonlr/argocd
  newTag: af1c44e4da1cf8821803440cdaefc3203b2a433f
